HOST aws-master
	HostName ec2-52-42-6-171.us-west-2.compute.amazonaws.com
	User ubuntu
	Port 22
	IdentityFile ~/.ssh/keys/aws/id_rsa_kube

HOST aws-mysql-data
	HostName ec2-35-80-194-134.us-west-2.compute.amazonaws.com
	User ubuntu
	Port 22
	IdentityFile ~/.ssh/keys/aws/id_rsa_kube
HOST aws-rmq
	HostName ec2-54-184-214-224.us-west-2.compute.amazonaws.com
	User ubuntu
	Port 22
	IdentityFile ~/.ssh/keys/aws/id_rsa_kube
HOST aws-mysql-common
	HostName ec2-54-188-200-164.us-west-2.compute.amazonaws.com
	User ubuntu
	Port 22
	IdentityFile ~/.ssh/keys/aws/id_rsa_kube

HOST aws-worker
	HostName 34.209.222.142
	User ubuntu
	Port 22
	IdentityFile ~/.ssh/keys/aws/id_rsa_kube
