Host desktop-home
	HostName 192.168.0.13
	Port 30405
	User jam
	IdentityFile ~/.ssh/keys/mydesktop/id

Host desktop-global
	HostName butterflygate.com
	User jam
	IdentityFile ~/.ssh/keys/mydesktop/id
	Port 30405

Host desktop-latona
	HostName 192.168.128.78
	User jam
	Port 30405
	IdentityFile ~/.ssh/keys/mydesktop/id
